/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

import java.sql.SQLException;
import util.Koneksi;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Kalkulator1 extends javax.swing.JFrame {
 Connection conn = (Connection) Koneksi.koneksiDB();
    ArrayList<String> arrayls = new ArrayList<String>();
 
    /**
     * Creates new form Kalkulator1
     */
    
    DefaultTableModel model;
    public Kalkulator1() {
        initComponents();
       
 
    }
    public void getData() {

        DefaultTableModel tabModel;
        Object[] row = {"Id", "Bilangan1", "Bilangan2", "Hasilnya"};
        tabModel = new DefaultTableModel(null, row);
        tb_data.setModel(tabModel);
        try {
            arrayls.clear();
            Statement st = conn.createStatement();
            String query = "SELECT * FROM tampilan ORDER BY id DESC";
            ResultSet set = st.executeQuery(query);

            int a = 1;
            while (set.next()) {
                String nomor, Bilangan1, Bilangan2, hasil, Id;

                Id = set.getString("id");
                nomor = String.valueOf(a + tabModel.getRowCount());
                Bilangan1 = set.getString("bil1");
                Bilangan2 = set.getString("bil2");
                hasil = set.getString("hasil");

                String[] data = {nomor, Bilangan1, Bilangan2,hasil, Id};
                tabModel.addRow(data);
                arrayls.add(Id.toString());
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }


  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_bilangan1 = new javax.swing.JTextField();
        tf_bilangan2 = new javax.swing.JTextField();
        Bilangan1 = new javax.swing.JLabel();
        Bilangan2 = new javax.swing.JLabel();
        Jawaban = new javax.swing.JLabel();
        Hasilnya = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        btn_kali = new javax.swing.JButton();
        btn_bagi = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_kurang = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setText("Kalkulator");

        Bilangan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Bilangan1.setText("Bilangan 1");

        Bilangan2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Bilangan2.setText("Bilangan 2");

        Jawaban.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Jawaban.setText("Hasilnya");

        Hasilnya.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Hasilnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilnyaActionPerformed(evt);
            }
        });

        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_data);

        btn_kali.setText("X");
        btn_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaliActionPerformed(evt);
            }
        });

        btn_bagi.setText("/");
        btn_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bagiActionPerformed(evt);
            }
        });

        btn_tambah.setText("+");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_kurang.setText("-");
        btn_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kurangActionPerformed(evt);
            }
        });

        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jawaban)
                                .addComponent(Bilangan2)
                                .addComponent(Bilangan1)
                                .addComponent(tf_bilangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_bilangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Hasilnya, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_kali)
                                .addGap(18, 18, 18)
                                .addComponent(btn_bagi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_tambah)
                                .addGap(8, 8, 8)))
                        .addComponent(btn_kurang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btn_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Bilangan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_bilangan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bilangan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_bilangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_kurang)
                    .addComponent(btn_bagi)
                    .addComponent(btn_kali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jawaban)
                .addGap(1, 1, 1)
                .addComponent(Hasilnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaliActionPerformed
        // TODO add your handling code here:
   int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a*b;
   Hasilnya.setText (Integer.toString (jumlah));
    }//GEN-LAST:event_btn_kaliActionPerformed

    private void btn_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bagiActionPerformed
        // TODO add your handling code here:
   int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a/b;
  Hasilnya.setText (Integer.toString (jumlah));
    }//GEN-LAST:event_btn_bagiActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
   int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a+b;
   Hasilnya.setText (Integer.toString (jumlah));
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kurangActionPerformed
        // TODO add your handling code here:
   int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a-b;
   Hasilnya.setText (Integer.toString (jumlah));
    }//GEN-LAST:event_btn_kurangActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        getData();
  
    }//GEN-LAST:event_formWindowActivated

    private void tb_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataMouseClicked
        // TODO add your handling code here:
        getData();
    }//GEN-LAST:event_tb_dataMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String bil1, bil2, hasil;
        bil1 = tf_bilangan1.getText();
        bil2 = tf_bilangan2.getText();
        hasil = Hasilnya.getText();
        if (bil1.isEmpty() || bil2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "tidak boleh ada yang kosong!");
        } else {
            try {
                Statement st = conn.createStatement();
                String query = "INSERT INTO `tampilan`(`bil1`, `bil2`, `hasil`) "
                        + "VALUES ('" + bil1 + "','" + bil2 + "','" + hasil + "')";
                int set = st.executeUpdate(query);
               getData();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
               
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void HasilnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilnyaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bilangan1;
    private javax.swing.JLabel Bilangan2;
    public javax.swing.JTextField Hasilnya;
    private javax.swing.JLabel Jawaban;
    private javax.swing.JButton btn_bagi;
    private javax.swing.JButton btn_kali;
    private javax.swing.JButton btn_kurang;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_data;
    public javax.swing.JTextField tf_bilangan1;
    public javax.swing.JTextField tf_bilangan2;
    // End of variables declaration//GEN-END:variables
public void getClear() {
        tf_bilangan1.setText("");
        tf_bilangan2.setText("");
    }
}
